First Name: FirstName
Last Name: LastName
# See linkedin for your country code, must be exact
Phone Country Code: Canada (+1)
Mobile Phone Number: 1234567890
Street address: 123 Fake Street
# Include the state/province as well!
City: Śląskie, Poland
State: Katowice
Zip: 41-214
Linkedin: https://www.linkedin.com/in/ongun-demirag
Website: https://www.ongundemirag.com/ # github/website is interchangable here

# How many years of "TECHNOLOGY" experience do you currently have? (whole numbers only)
experience do you currently have:
  Accounting/Auditing: 0
  Administrative: 0
  Advertising: 0
  Analyst: 0
  Art/Creative: 0
  Business Development: 1
  Consulting: 0
  Customer Service: 0
  Distribution Design: 0
  Education: 0
  Engineering: 3
  Finance: 0
  General Business: 2
  Health Care Provider: 0
  Human Resources: 0
  Information Technology: 0
  Legal: 0
  Management: 1
  Manufacturing: 0
  Marketing: 0
  Public Relations: 0
  Purchasing: 0
  Product Management: 2
  Project Management: 3
  Production: 0
  Quality Assurance: 0
  Research: 0
  Sales: 0
  Science: 0
  Strategy/Planning: 0
  Supply Chain: 0
  Training: 0
  Writing/Editing: 0
  # default to put for any skill that you did not list
  default: 0
  # end normal ones, put your custom ones here
  C++: 0
  Python: 3
  Javascript: 3
  # Node: 3
  # -- end of experience do you currently have, bot added ones below

# Questions having these technology keywords inside (whole numbers only) - case insensitive
python: 3
Spring Boot: 0
java: 3
PHP: 0
Laravel: 0
SASS: 3
React: 3
React Native: 2
Django: 0
SAP: 0
ipt: 0
MySQL: 0
Shopify: 0
Typescript: 3
JavaScript: 3
Angular: 0
Redux.js: 2
Angular Command Line Interface (CLI): 0
selenium: 3
C++: 0
C#: 0
C (Programming Language): 0
Software Development: 3
Linux: 2
Cross-functional team: 0
Social media platforms: 0
Microsoft Azure: 0
AWS: 0
.NET: 0
# add custom one here

universityGpa: 4.0

# What is your level of proficiency in a: polski? Required
level of proficiency:
  english: Native or bilingual # None, Conversational, Professional, Native or bilingual
  polski: Conversational # None, Conversational, Professional, Native or bilingual

# Other queations, you can add custom ones below and bot will also add the unrecognized ones at the end
# Can you provide a ballpark salary range you'd be looking for? Required / # Desired salary Required / Salary expectations for / # what is your salary expectation? / # cuál es su expectativa salarial en usd?
Salary range: 15000 usd - 18000 usd net monthly.
Desired salary: 15000 usd - 18000 usd net monthly.
Salary expectation: 15000
salarial: 15000
# If you selected Word of mouth, Referral or Other from the question above, please specify in the box below.
Word of mouth, Referral or Other: None
# College or University
College or University: ABC University
# Have you ever applied at ... before? Required
Have you ever applied: "No"
#  Please provide 3 references with their name, phone number, and email address. Required
References: A, 045,abc@gmail.com | B,234,abc@gmail.com | C,2134,abc@gmail.com
#  How many hours are you available every week? Required
Hours are you available every week: 40
#  What is your desired hourly pay rate (in USD)? Required
Hourly pay rate: 30
#  Notice period in weeks Required
Notice period: 2 weeks
#  Please evaluate on a scale from 1 to 10 you ability to manage technical issues on different social media platforms? Required
Manage Technical Issues: 8
# What are your salary requirements in gross monthly PLN?
gross monthly PLN: 32269
# Unanswered questions from the bot will go below you can write your answer after ":" For example How many years of x experience you have:5
# how many years of work experience do you have with programming languages?
programming languages: 5
# how many years of work experience do you have with internet of things (iot)?
internet of things (iot): 1
# how many years of work experience do you have with opencv?
opencv: 0
# how many years of work experience do you have with numpy?
numpy: 3
# please specify ... based questions
Please specify: --
# ile lat posługujesz się zawodowo narzędziem prestashop? - how many years have you been using the prestashop tool professionally?
prestashop: 0
# how many years of work experience do you have with web 2.0?
web 2.0: 5
# how many years of work experience do you have with wpf development?
wpf: 0
# how many years of work experience do you have with microsoft sql server?
sql: 0
# how many years of work experience do you have with web testing?
web testing: 2
# ile lat posługujesz się zawodowo narzędziem routery cisco? - how many years have you been using cisco routers professionally?
cisco: 0
# ile lat posługujesz się zawodowo narzędziem sieć lokalna (lan)? - how many years have you been using the local network (LAN) tool professionally?
lan: 0
# what is your university grade point average (4.0 gpa scale)?
gpa: 3
# how many years of work experience do you have with dashboard building?
dashboard building: 2
# how many years of work experience do you have with database-driven web applications?
database-driven web applications: 2
# how many years of work experience do you have with data science?
data science: 1
# let us know which specific channel/event/medium/etc you heard about us: # how did you hear about this job?
heard about us: Linkedin
hear: Linkedin
# how many years of work experience do you have with amazon sqs?
amazon sqs: 0
# experience with sre?
sre: 0
# experience with nodejs?
nodejs: 3
# experience as developer (full stack)?
developer: 3
# location

# when would you be available to start a new role?

# do you have 3-5 years of experience in graphic design
3-5 years of experience in graphic design: "No"
# how many years of experience do you have?
how many years of experience do you have?: 5
# how many years of work experience do you have with snowflake?
snowflake: 0
# do you have with azure databricks?
azure databricks: 0
# How many years of experience as a web developer do you have?
web developer: 5
# how many years of work experience do you have with figma (software)?
Figma: 2
# how many years of work experience do you have with responsive web design?
Responsive web design: 3
# how many years of work experience do you have with extract, transform, load (etl)?
extract, transform, load: 0
# how many years of work experience do you have with data modeling?
data modeling: 0
# how many years of work experience do you have with sitecore?
sitecore: 0
# how many years of work experience do you have with servlets?
servlets: 0
